"""
Preprocessing for the film poster images shown on director profile pages
(site/director.html "Select Films Directed by <X>" section).

Poster images live outside this repo, in the sibling ReelWrangling project's
IMDb poster pipeline output:

    ../ReelWrangling/data/film_posters/<Director_Name>/<Film Title>.<ext>

This script:
  1. Matches each poster file to a film in window.FILMS (site/assets/films-data.js)
     by director + normalized title, using the same slugify/splitDirectors
     rules as site/assets/director-utils.js (ported here so matching is
     deterministic without a JS runtime).
  2. Copies matched posters into site/assets/posters/<tconst>.<ext> (flat,
     keyed by tconst so the runtime lookup in director-profile.js doesn't
     need to know about director folder names or filename spelling).
  3. Writes site/assets/poster-map.js:  window.POSTER_MAP = {tconst: path, ...}

Re-running it is safe -- it just recomputes the copy and the map from
scratch each time. Prints a report of anything that didn't match cleanly
(a poster director folder with no matching director in the dataset, a
poster file whose name doesn't match any of that director's film titles,
or a film by a poster-having director with no poster file), so new posters
that don't line up get flagged instead of silently skipped.

Usage:
    python3 build_poster_map.py
"""

import json
import re
import shutil
import unicodedata
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SITE_ASSETS = REPO_ROOT / "site" / "assets"
FILMS_DATA_PATH = SITE_ASSETS / "films-data.js"
POSTERS_SOURCE = REPO_ROOT.parent / "ReelWrangling" / "data" / "film_posters"
POSTERS_DEST = SITE_ASSETS / "posters"
MAP_PATH = SITE_ASSETS / "poster-map.js"


def strip_diacritics(s):
    return "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))


def slugify(name):
    n = strip_diacritics(name).lower()
    n = n.replace("'", "").replace("’", "").replace(".", "")
    n = re.sub(r"[^a-z0-9]+", "-", n).strip("-")
    return n or "unknown"


def split_directors(raw):
    if not raw:
        return []
    normalized = re.sub(r"\s*,?\s+and\s+", ", ", raw, flags=re.I)
    seen = set()
    out = []
    for part in normalized.split(","):
        name = part.strip()
        if name and name not in seen:
            seen.add(name)
            out.append(name)
    return out


def norm_title(s):
    s = strip_diacritics(s).lower()
    s = s.replace("’", "'")
    s = re.sub(r"[^a-z0-9]+", " ", s).strip()
    return s


def load_films():
    text = FILMS_DATA_PATH.read_text()
    m = re.search(r"window\.FILMS = (\[.*?\]);\n", text, re.S)
    return json.loads(m.group(1))


def main():
    films = load_films()

    director_films = defaultdict(list)
    for f in films:
        for name in split_directors(f.get("director") or ""):
            director_films[slugify(name)].append(f)

    poster_dirs = sorted(
        d.name for d in POSTERS_SOURCE.iterdir() if d.is_dir()
    )

    unmatched_poster_dirs = []
    unmatched_posters = []
    missing_posters = []
    poster_map = {}

    if POSTERS_DEST.exists():
        shutil.rmtree(POSTERS_DEST)
    POSTERS_DEST.mkdir(parents=True)

    for d in poster_dirs:
        folder_slug = slugify(d.replace("_", " "))
        dfilms = director_films.get(folder_slug)
        if not dfilms:
            unmatched_poster_dirs.append(d)
            continue

        film_by_norm = defaultdict(list)
        for f in dfilms:
            film_by_norm[norm_title(f["title"])].append(f)

        used_tconsts = set()
        src_dir = POSTERS_SOURCE / d
        poster_files = sorted(p for p in src_dir.iterdir() if p.is_file() and not p.name.startswith("."))

        for pf in poster_files:
            key = norm_title(pf.stem)
            cands = film_by_norm.get(key)
            if not cands:
                unmatched_posters.append((d, pf.name))
                continue
            chosen = next((c for c in cands if c["t"] not in used_tconsts), cands[0])
            used_tconsts.add(chosen["t"])

            dest_name = f"{chosen['t']}{pf.suffix.lower()}"
            shutil.copyfile(pf, POSTERS_DEST / dest_name)
            poster_map[chosen["t"]] = f"assets/posters/{dest_name}"

        for f in dfilms:
            if f["t"] not in used_tconsts:
                missing_posters.append((d, f["title"], f["year"], f["t"]))

    MAP_PATH.write_text(
        "// Generated by src/build_poster_map.py -- do not hand-edit.\n"
        "// Maps a film's tconst to its poster image path, for films whose\n"
        "// director has poster art available (see data/film_posters in the\n"
        "// sibling ReelWrangling repo). Films with no entry here fall back to\n"
        "// assets/poster-placeholder.svg (see director-profile.js).\n"
        f"window.POSTER_MAP = {json.dumps(poster_map, sort_keys=True, indent=2)};\n"
    )

    print(f"Matched {len(poster_map)} poster -> film pairs across {len(poster_dirs) - len(unmatched_poster_dirs)} directors.")
    print(f"Wrote {MAP_PATH.relative_to(REPO_ROOT)}")
    print(f"Copied posters into {POSTERS_DEST.relative_to(REPO_ROOT)}")

    if unmatched_poster_dirs:
        print("\nPoster director folders with NO matching director in the dataset:")
        for d in unmatched_poster_dirs:
            print(f"  {d}")

    if unmatched_posters:
        print("\nPoster files that could not be matched to a film title:")
        for d, pf in unmatched_posters:
            print(f"  [{d}] {pf}")

    if missing_posters:
        print("\nFilms by a poster-having director with no poster file:")
        for d, title, year, t in missing_posters:
            print(f"  [{d}] {title} ({year}) [{t}]")

    if not (unmatched_poster_dirs or unmatched_posters or missing_posters):
        print("\nNo mismatches -- every poster matched exactly one film.")


if __name__ == "__main__":
    main()
