"""
Generates a file://-compatible fallback for the director profile page's
cluster network visualizations.

site/director-profile.js normally loads each cluster's node-network SVG
with fetch(), which is efficient (only the clusters a given director
actually appears in are downloaded) but Chrome (and most browsers) refuse
fetch() of local files when a page is opened directly as a file:// URL --
there's no server to ask, so it's treated as unsupported/cross-origin and
the request fails outright. That's a browser security restriction, not
something a static site can turn off.

Regular resource loads (script/img/link) are NOT restricted this way under
file://, so this script pre-encodes each cluster's SVG source as a JS
string in its own small file under site/assets/svg-fallback/. When
fetch() fails, director-profile.js inserts the matching <script> tag
instead, which works identically under file://, http://, and https://.

Only generated for the 10 clusters that have a node-network SVG (see
CLUSTER_VIZ_SVG in site/assets/director-utils.js -- kept in sync with that
list here). hiddenGems has no SVG and needs no fallback.

Usage:
    python3 build_svg_fallback.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
ASSETS_DIR = REPO_ROOT / "site" / "assets"
OUT_DIR = ASSETS_DIR / "svg-fallback"

# Must match CLUSTER_VIZ_SVG in site/assets/director-utils.js.
CLUSTER_VIZ_SVG = {
    "anglophone_classic": "anglophone_classic_rings.svg",
    "bergman_scandinavian": "bergman_scandinavian_rings.svg",
    "czech_new_wave": "czech_new_wave_graph.svg",
    "european_art_cinema": "european_art_cinema_rings.svg",
    "hong_kong_taiwan_cinema": "hong_kong_taiwan_cinema_rings.svg",
    "japanese_cinema": "japanese_cinema_rings.svg",
    "satyajit_ray_indian": "satyajit_ray_indian_graph.svg",
    "soviet_cinema": "soviet_cinema_graph.svg",
    "transatlantic_auteur_cinema": "transatlantic_auteur_cinema_rings.svg",
    "youssef_chahine_egyptian": "youssef_chahine_egyptian_graph.svg",
}


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    total_in = 0
    total_out = 0
    for cluster_id, svg_name in CLUSTER_VIZ_SVG.items():
        svg_path = ASSETS_DIR / svg_name
        svg_text = svg_path.read_text(encoding="utf-8")
        total_in += len(svg_text.encode("utf-8"))

        js = (
            "// Generated by src/build_svg_fallback.py -- do not hand-edit.\n"
            "// file://-compatible copy of assets/" + svg_name + ", loaded via a\n"
            "// <script> tag (not fetch()) when director-profile.js detects fetch()\n"
            "// can't reach local files (e.g. the page was opened directly from disk).\n"
            "window.__SVG_FALLBACK__ = window.__SVG_FALLBACK__ || {};\n"
            f"window.__SVG_FALLBACK__[{json.dumps(cluster_id)}] = {json.dumps(svg_text, ensure_ascii=False)};\n"
        )
        out_path = OUT_DIR / (cluster_id + ".js")
        out_path.write_text(js, encoding="utf-8")
        total_out += len(js.encode("utf-8"))

    print(f"Wrote {len(CLUSTER_VIZ_SVG)} fallback file(s) to {OUT_DIR}")
    print(f"Source SVGs: {total_in / 1024:.0f} KB -> fallback JS: {total_out / 1024:.0f} KB")


if __name__ == "__main__":
    main()
