"""
Regenerates output/small_cluster_analysis.md: a profile of every raw Louvain
community that fell under MIN_NAMED_CLUSTER_SIZE and got folded into
hiddenGems by src/cluster.py, so that "why is this film in Hidden Gems"
has a real, evidence-based answer instead of just "too small to name."

Communities of 3+ films get a full profile (dominant director(s)/country,
representative films by internal degree, internal/external edge ratio);
2-film communities are summarized in the table only, same convention as the
original hand-authored version of this file. Unlike that version (written
for one specific pre-2026-07-31 Louvain run and left to go stale), this is a
script -- rerun any time cluster.py's community structure changes.

    python3 build_small_cluster_analysis.py
"""

from collections import Counter
from pathlib import Path

import duckdb
import pandas as pd

from cluster import build_graph, run_louvain, MIN_NAMED_CLUSTER_SIZE
from cluster_graph_viz import DB_PATH

OUT_PATH = Path(__file__).parent.parent / "output" / "small_cluster_analysis.md"


def load_basic(con):
    return con.execute("""
        SELECT imdb_tconst, title, criterion_director, criterion_year, criterion_country
        FROM (
            SELECT *, row_number() OVER (
                PARTITION BY imdb_tconst
                ORDER BY (source = 'best_picture_nominee') ASC, confidence_score DESC NULLS LAST
            ) AS rn
            FROM criterion_basic_info
        ) WHERE rn = 1
    """).df().set_index("imdb_tconst")


def main():
    con = duckdb.connect(str(DB_PATH), read_only=True)
    G = build_graph(con)
    partition = run_louvain(G)
    basic = load_basic(con)
    con.close()

    sizes = Counter(partition.values())
    small_ids = [cid for cid, s in sizes.items() if s < MIN_NAMED_CLUSTER_SIZE]

    internal, external = Counter(), Counter()
    for u, v, data in G.edges(data=True):
        cu, cv = partition[u], partition[v]
        if cu == cv:
            internal[cu] += 1
        else:
            external[cu] += 1
            external[cv] += 1
    degree = dict(G.degree())

    rows = []
    for cid in small_ids:
        members = [t for t, c in partition.items() if c == cid]
        ie, ee = internal[cid], external[cid]
        ratio = ie / (ie + ee) if (ie + ee) else 1.0
        rows.append((cid, len(members), ie, ee, ratio, members))
    rows.sort(key=lambda r: (-r[1], -r[4]))

    n_full_internal = sum(1 for r in rows if r[4] == 1.0)
    total_films = sum(r[1] for r in rows)

    lines = [
        f"# Small Cluster Analysis (< {MIN_NAMED_CLUSTER_SIZE} Films)",
        "",
        f"Generated by src/build_small_cluster_analysis.py from the 2026-07-31 "
        f"post-Best-Picture-import Louvain run (random_state=42). {len(rows)} "
        f"raw communities fall under the {MIN_NAMED_CLUSTER_SIZE}-film named-cluster "
        f"floor (see src/cluster.py), covering {total_films} films folded into "
        f"Hidden Gems. {n_full_internal} of {len(rows)} ({n_full_internal/len(rows)*100:.0f}%) "
        f"have a 100% internal edge ratio -- no shared actors with any film "
        f"outside the community.",
        "",
        "---",
        "",
        "## Edge Statistics",
        "",
        "| Community | Films | Internal | External | Internal Ratio |",
        "|---|---|---|---|---|",
    ]
    for cid, size, ie, ee, ratio, _members in rows:
        lines.append(f"| {cid} | {size} | {ie} | {ee} | {ratio*100:.1f}% |")

    lines += ["", "---", "", "## Cluster Profiles", ""]

    profiled = [r for r in rows if r[1] >= 3]
    for cid, size, ie, ee, ratio, members in profiled:
        directors = Counter()
        countries = Counter()
        for t in members:
            if t in basic.index:
                d, c = basic.loc[t, "criterion_director"], basic.loc[t, "criterion_country"]
                if pd.notna(d):
                    directors[d] += 1
                if pd.notna(c):
                    countries[c] += 1
        top_director = directors.most_common(1)
        label_bits = []
        if top_director and top_director[0][1] >= max(2, size // 2):
            label_bits.append(top_director[0][0])
        if countries:
            top_country, top_count = countries.most_common(1)[0]
            # Require the majority of the WHOLE community (not just of
            # whatever subset happens to carry country data) to avoid a
            # single stray value labeling a community "X cinema" off one
            # thinly-covered film -- e.g. 1-of-3 films tagged Canada
            # shouldn't caption a mostly-American community "Canada cinema".
            if top_count == sum(countries.values()) and len(countries) == 1 and top_count >= max(2, size // 2):
                label_bits.append(top_country + " cinema")
        label = " / ".join(label_bits) if label_bits else "Mixed"

        ranked = sorted(members, key=lambda t: -degree.get(t, 0))
        film_bits = []
        for t in ranked:
            title = basic.loc[t, "title"] if t in basic.index else t
            year = (int(basic.loc[t, "criterion_year"])
                    if t in basic.index and pd.notna(basic.loc[t, "criterion_year"]) else None)
            film_bits.append(f"*{title}*" + (f" ({year})" if year else ""))

        lines.append(f"### Community {cid} — {label} ({size} films, {ie} internal / {ee} external, {ratio*100:.1f}%)")
        if directors:
            dir_str = ", ".join(f"{d} ({n})" for d, n in directors.most_common(5))
            lines.append(f"Directors: {dir_str}.")
        if countries:
            c_str = ", ".join(f"{c} ({n})" for c, n in countries.most_common(5))
            lines.append(f"Countries: {c_str}.")
        lines.append(f"Films by internal shared-actor degree: {', '.join(film_bits)}.")
        lines.append("")

    two_film = [r for r in rows if r[1] == 2]
    if two_film:
        lines += [
            f"{len(two_film)} additional 2-film communities (each an isolated pair "
            f"linked by a single shared actor) are listed in the Edge Statistics "
            f"table above but not profiled individually.",
            "",
        ]

    lines += ["---", "", "## Key Findings", ""]
    lines.append(
        f"**Self-containment is near-universal.** {n_full_internal} of {len(rows)} "
        f"communities ({n_full_internal/len(rows)*100:.0f}%) have a 100% internal "
        f"ratio -- no shared actors with any other community."
    )
    single_director = [r for r in profiled
                        if (Counter(basic.loc[t, "criterion_director"] for t in r[5]
                                    if t in basic.index and pd.notna(basic.loc[t, "criterion_director"]))
                            .most_common(1) or [(None, 0)])[0][1] >= max(2, r[1] // 2)]
    lines.append(
        f"\n**Director filmographies dominate.** {len(single_director)} of the "
        f"{len(profiled)} profiled (3+ film) communities are majority-led by a "
        f"single director's own filmography."
    )
    single_country = [r for r in profiled
                       if len(Counter(basic.loc[t, 'criterion_country'] for t in r[5]
                                       if t in basic.index and pd.notna(basic.loc[t, 'criterion_country']))) == 1]
    lines.append(
        f"\n**National cinema boundaries hold for many.** {len(single_country)} of "
        f"the {len(profiled)} profiled communities draw every film with recorded "
        f"country data from a single country."
    )

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(rows)} communities ({profiled and len(profiled) or 0} profiled) to {OUT_PATH}")


if __name__ == "__main__":
    main()
